name: Increment Tag

on:
  push:
    branches:
      - main

jobs:
  test_1:
    runs-on: ubuntu-latest
    steps:
      - name: Get commit sha associated with tag
        run: |
          commit_sha=(git rev-list -n 1 v0.0.1)
          echo "COMMIT_SHA=${commit_sha}" >> $GITHUB_ENV

      - name: print commit sha
        run: |
          echo "testiong"
          echo $COMMIT_SHA
  
