name: Increment Tag

on:
  push:
    branches:
      - main

jobs:
  job_1:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - name: set output tag
        id: tag_version
        run: |
          echo "::set-output name=new_tag::v0.0.1"
    
  test_1:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit sha associated with tag
        run: |
          git fetch --tags
          commit_sha=$(git rev-list -n 1 ${{ needs.job_1.outputs.new_tag }})
          echo "COMMIT_SHA=${commit_sha}" >> $GITHUB_ENV

      - name: print commit sha
        run: |
          echo $COMMIT_SHA
  
